### ISSUE TITLE
Document support of out of cluster installation

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles-docs#13]
Following on from https://github.com/rancher-sandbox/rancher-turtles/issues/19 and https://github.com/rancher-sandbox/rancher-turtles/pull/82#pullrequestreview-1604952523, we need to create documentation on what's required to run Rancher Turtles out of the Rancher Manager cluster, including:
- Handling the RBAC, service account, etc.
- How to create the secret and mount it.

**Comment by furkatgofurov7** [comment]
@salasberryfin is this something we can do at this point and should be put on hold/block, considering the support of out of cluster installation is not supported yet?

**Comment by salasberryfin** [comment]
I think this needs to be put on hold for now. This was probably created when we published the original ADR.

**Comment by furkatgofurov7** [comment]
This can be closed and not planned to be implemented hence not to be documented
