### ISSUE TITLE
Migrate Turtles docs to AsciiDoc based Antora

### ISSUE THREAD

**Issue by furkatgofurov7** [rancher/turtles-docs#162]
Recently we started the process of syncing current repo documentation with [Product Documentation](https://documentation.suse.com/cloudnative/cluster-api/) which under the hood lives in https://github.com/rancher/turtles-product-docs repo. 

turtles-product-docs repo is using [Antora](https://antora.org/) AsciiDoc based multi-repository documentation site generator. More info on how it is build: https://github.com/rancher/turtles-product-docs/blob/main/README.md

In the future, all repositories including this repo might need to be migrated away from Docusaurus to Antora to align with product docs and to have a single documentation generator tool across the org and this issue is for tracking the future migration.

**Comment by furkatgofurov7** [comment]
@kkaempf FYI after the offline discussion with you and the team.

**Comment by alexander-demicev** [comment]
Closing as resolved
