### ISSUE TITLE
Document versioning support for Rancher turtles

### ISSUE THREAD

**Issue by furkatgofurov7** [rancher/turtles-docs#42]
As a developer/user/operator I want to clearly document versioning support for Rancher Turtles so that consumers of the operator are aware of the support matrix (i.e if there are v0.1/2/3/4/5 minor release versions, we do support only the latest-2 minor releases) we guarantee.

**Comment by valaparthvi** [comment]
I believe this has been implemented, no?

**Comment by furkatgofurov7** [comment]
I think it was covered in https://github.com/rancher/turtles/blob/main/docs/release.md#support-and-guarantees
