### ISSUE TITLE
CAPI Docs - Site Standardization & Rancher Integration

### ISSUE THREAD

**Issue by sunilarjun** [rancher/turtles-docs#64]
The [Cluster API documentation](https://docs.rancher-turtles.com/docs/intro) needs adjustments to align with SUSE standards and be updated as an item in the [Integrations in Rancher](https://ranchermanager.docs.rancher.com/integrations-in-rancher) sub-header for Rancher Manager.

Action Items:

- [x] Change URL to standard Rancher schema "turtles.docs.rancher.com" (https://github.com/rancher/turtles-docs/pull/70)
- [x] Remove current landing page and have URL "turtles.docs.rancher.com" land directly on documentation site. (https://github.com/rancher/turtles-docs/pull/69)
- [x] Add "Cluster API with Rancher Turtles" under "Integrations in Rancher" section including "Overview" page (https://github.com/rancher/rancher-docs/pull/1216)
- [x] Initial content review and adjustments ([Docusaurus v3.2.1 Update](https://github.com/rancher/turtles-docs/pull/86))
- [x] If time permits, add local search capability (https://github.com/rancher/turtles-docs/pull/89)

Not able to assign myself but I will be handling this issue.

**Comment by gunamata** [comment]
Thanks Sunil.
Looping @kkaempf , @davidstauffer , @mbologna if we need any information as we move forward.

**Comment by kkaempf** [comment]
> 
> Not able to assign myself but I will be handling this issue.

You should have full access now @sunilarjun

**Comment by sunilarjun** [comment]
Closing issue as all action items have been merged in, thank you!
