### ISSUE TITLE
RKE2 Documentation

### ISSUE THREAD

**Issue by Daemonslayer2048** [rancher/turtles-docs#71]
Is there any mechanism available that could allow turtles to deploy RKE2 clusters? Digging around I am struggling to find any information on how or if turtles can even be used to deploy RKE2 clusters. In my example I am attempting to deploy to vsphere, I saw some references to kubeadm so I assume the default is to deploy RKE, is this all accurate?

**Comment by richardcase** [comment]
Thanks @Daemonslayer2048 . You could use the [CAPRKE2 providers](https://github.com/rancher-sandbox/cluster-api-provider-rke2) with Rancher Turtles.  Using CAPRKE2 is different to creating an RKE2 cluster with the existing provisioning mechanisms in Rancher in that it doesn't currently support any of the day 2 operations (i.e. etcd snapshot restore, cert rotation). If you car about those types of day 2 operations with RKE2 then its best to use the existing provisioning mechanisms.

Are you currently part of the early adopter programme for Rancher Turtles?

**Comment by Daemonslayer2048** [comment]
Hey @richardcase, I am not part of the early adopter program. My Github profile does not really show it much but I am a Rancher Government Solutions employee, I am looking into Turtles and as you can imagine I have a particular interest in RKE2. My hope was Turtles docs could keep RKE2 deployments in mind, and preferably provide some docs on how this could be done.

**Comment by richardcase** [comment]
Thanks @Daemonslayer2048 - Rancher Turtles will certainly be keeping RKE2 in mind :wink:  . Lets chat.
