### ISSUE TITLE
[RFE] Searching the docs

### ISSUE THREAD

**Issue by valaparthvi** [rancher/turtles-docs#80]
As a user, having a functionality to search the document will make the experience of reading the doc easier, especially since the doc website is a work in progress.

Ref: https://docusaurus.io/docs/search

**Comment by furkatgofurov7** [comment]
@valaparthvi this will be covered as part of https://github.com/rancher/turtles-docs/issues/64 (last item in the list), and I am closing this issue in favor of 64 to avoid duplicate issues. 

Feel free to re-open if needed.
